In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from scipy.special import erfc
#from imblearn.over_sampling import SMOTE
import os

In [2]:
os.getcwd()
os.chdir('C:\\Amazon\\Learning\\Analytics Path_Py\\Kaggle Projects\\Predict number of upvotes')
os.getcwd()
df1 = pd.read_csv('train.csv')
df1.head()

ID Tag  Reputation  Answers  Username    Views  Upvotes
0   52664   a      3942.0      2.0    155623   7855.0     42.0
1  327662   a     26046.0     12.0     21781  55801.0   1175.0
2  468453   c      1358.0      4.0     56177   8067.0     60.0
3   96996   a       264.0      3.0    168793  27064.0      9.0
4  131465   c      4271.0      4.0    112223  13986.0     83.0

In [4]:
df1.info() ## 330045 rows, no null value

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 330045 entries, 0 to 330044
Data columns (total 7 columns):
ID            330045 non-null int64
Tag           330045 non-null object
Reputation    330045 non-null float64
Answers       330045 non-null float64
Username      330045 non-null int64
Views         330045 non-null float64
Upvotes       330045 non-null float64
dtypes: float64(4), int64(2), object(1)
memory usage: 17.6+ MB


In [5]:
print('Unique values in Tag: ', df1['Tag'].unique().tolist())
##print('Unique values in Username: ', df1['Username'].unique().tolist())
##Lacs of unique values in UserName, so will not use this column


Unique values in Tag:  ['a', 'c', 'r', 'j', 'p', 's', 'h', 'o', 'i', 'x']


In [7]:
df = df1.copy()
df.drop(['ID','Username'], axis=1,inplace=True)

In [8]:
df.head()

Tag  Reputation  Answers    Views  Upvotes
0   a      3942.0      2.0   7855.0     42.0
1   a     26046.0     12.0  55801.0   1175.0
2   c      1358.0      4.0   8067.0     60.0
3   a       264.0      3.0  27064.0      9.0
4   c      4271.0      4.0  13986.0     83.0

## LabelEncoding

In [9]:
## Convert tag into dummies.
from sklearn.preprocessing import OneHotEncoder, LabelEncoder
Le = LabelEncoder()
df['Tag'] = Le.fit_transform(df['Tag']) ## total 9 levels so 8 dummy columns


In [10]:
print(df['Tag'].shape)
print(df['Tag'].dtype)
#df['Tag']

(330045,)
int32


In [11]:
df.head()
print('Unique values in Tag: ', df['Tag'].unique().tolist())

Unique values in Tag:  [0, 1, 7, 4, 6, 8, 2, 5, 3, 9]


In [62]:
# One way to convert tag column to dummies is: fit tag column to lableencoder, reshape it and convert it to onehotencoder
#integer_encoded = Tag1.reshape(len(Tag1), 1)
#print(integer_encoded.shape)
#print(integer_encoded.dtype)
#integer_encoded

In [12]:
df2 = df.copy()
df2.head()

Tag  Reputation  Answers    Views  Upvotes
0    0      3942.0      2.0   7855.0     42.0
1    0     26046.0     12.0  55801.0   1175.0
2    1      1358.0      4.0   8067.0     60.0
3    0       264.0      3.0  27064.0      9.0
4    1      4271.0      4.0  13986.0     83.0

In [13]:
## Converting a  data frame to ndarray
#recover df from here if anything goes wrong
df = df2.copy()
df.head()

Tag  Reputation  Answers    Views  Upvotes
0    0      3942.0      2.0   7855.0     42.0
1    0     26046.0     12.0  55801.0   1175.0
2    1      1358.0      4.0   8067.0     60.0
3    0       264.0      3.0  27064.0      9.0
4    1      4271.0      4.0  13986.0     83.0

In [15]:
df.describe()

Tag    Reputation        Answers         Views        Upvotes
count  330045.00000  3.300450e+05  330045.000000  3.300450e+05  330045.000000
mean        3.54305  7.773147e+03       3.917672  2.964507e+04     337.505358
std         2.49392  2.706141e+04       3.579515  8.095646e+04    3592.441135
min         0.00000  0.000000e+00       0.000000  9.000000e+00       0.000000
25%         1.00000  2.820000e+02       2.000000  2.594000e+03       8.000000
50%         4.00000  1.236000e+03       3.000000  8.954000e+03      28.000000
75%         6.00000  5.118000e+03       5.000000  2.687000e+04     107.000000
max         9.00000  1.042428e+06      76.000000  5.231058e+06  615278.000000

In [16]:
df.corr()

Tag  Reputation   Answers     Views   Upvotes
Tag         1.000000   -0.024017 -0.064710 -0.011807 -0.004300
Reputation -0.024017    1.000000  0.066504  0.036455  0.266710
Answers    -0.064710    0.066504  1.000000  0.498642  0.202033
Views      -0.011807    0.036455  0.498642  1.000000  0.437336
Upvotes    -0.004300    0.266710  0.202033  0.437336  1.000000

In [17]:
Upvotes  = df['Upvotes']
df.drop(['Upvotes'], axis =1, inplace = True)

In [18]:
df.head()

Tag  Reputation  Answers    Views
0    0      3942.0      2.0   7855.0
1    0     26046.0     12.0  55801.0
2    1      1358.0      4.0   8067.0
3    0       264.0      3.0  27064.0
4    1      4271.0      4.0  13986.0

## X and Y split

In [22]:
X = df.values
Y = Upvotes

In [23]:
X[0:2]

array([[0.0000e+00, 3.9420e+03, 2.0000e+00, 7.8550e+03],
       [0.0000e+00, 2.6046e+04, 1.2000e+01, 5.5801e+04]])

## OneHotEncoding

In [24]:
Ohencoder  = OneHotEncoder(categorical_features =[0])
X = Ohencoder.fit_transform(X).toarray()
##df= df.toarray()

C:\Users\singhxyp\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\singhxyp\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:390: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [25]:
X[0:3]

array([[1.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        3.9420e+03, 2.0000e+00, 7.8550e+03],
       [1.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        2.6046e+04, 1.2000e+01, 5.5801e+04],
       [0.0000e+00, 1.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        1.3580e+03, 4.0000e+00, 8.0670e+03]])

In [26]:
x_train, x_test, y_train, y_test = train_test_split(X,Y, test_size = 0.2, random_state = 7)

In [27]:
print(len(x_train))
print(len(x_test))
print(len(y_train))
print(len(y_test))

264036
66009
264036
66009


In [28]:
x_train[0:2]

array([[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 1.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        4.8000e+01, 1.0000e+00, 6.0833e+04],
       [1.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        2.7000e+02, 4.0000e+00, 2.8124e+04]])

In [29]:
x_train = pd.DataFrame(x_train)
x_test = pd.DataFrame(x_test)

In [30]:
x_train.head()

0    1    2    3    4    5    6    7    8    9       10   11       12
0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0    48.0  1.0  60833.0
1  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   270.0  4.0  28124.0
2  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1698.0  1.0  65733.0
3  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  2005.0  2.0    245.0
4  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0   776.0  7.0  88749.0

In [31]:
y_train.head()

266546      6.0
266928     29.0
266868    156.0
301954      3.0
41703     187.0
Name: Upvotes, dtype: float64

## Scaling Target Variable

In [37]:
#sc1 = StandardScaler()
#y_train2 = y_train.values
#y_train1= y_train2.reshape(-1, 1)
#y_train1 = sc1.fit_transform(y_train1)
#y_train1[0:6]

# Random Forest Classifier

In [32]:
# Importing the Random Forest 
from sklearn.ensemble import RandomForestRegressor

RF = RandomForestRegressor(n_estimators= 200, random_state= 7, n_jobs =1)
print(RF.get_params())

{'bootstrap': True, 'criterion': 'mse', 'max_depth': None, 'max_features': 'auto', 'max_leaf_nodes': None, 'min_impurity_decrease': 0.0, 'min_impurity_split': None, 'min_samples_leaf': 1, 'min_samples_split': 2, 'min_weight_fraction_leaf': 0.0, 'n_estimators': 200, 'n_jobs': 1, 'oob_score': False, 'random_state': 7, 'verbose': 0, 'warm_start': False}


In [33]:
RF.fit(x_train, y_train)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=200, n_jobs=1,
           oob_score=False, random_state=7, verbose=0, warm_start=False)

## Prediction on Train Data

In [34]:
y_pred_tr=RF.predict(x_train)

In [241]:
## Inverse Scaling of target to match the original y_train
##y_pred_tr = sc1.inverse_transform(y_pred_tr_scale)

In [35]:
##Evaluation

from sklearn import metrics

print(metrics.mean_absolute_error(y_train,y_pred_tr))

print(metrics.mean_squared_error(y_train,y_pred_tr))

print(np.sqrt(metrics.mean_squared_error(y_train,y_pred_tr)))

print(metrics.r2_score(y_train,y_pred_tr))

40.54639280046769
236714.66588955413
486.5333142648652
0.9832170320126782


## Prediction on Test Data

In [36]:
y_pred_test=RF.predict(x_test)

In [255]:
## Inverse Scaling of target to match the original y_train
##y_pred_test = sc1.inverse_transform(y_pred_test_sc)

In [37]:
##Evaluation

from sklearn import metrics

print(metrics.mean_absolute_error(y_test,y_pred_test))

print(metrics.mean_squared_error(y_test,y_pred_test))

print(np.sqrt(metrics.mean_squared_error(y_test,y_pred_test)))

print(metrics.r2_score(y_test,y_pred_test))

108.51888842232192
1257871.8468209484
1121.5488606480542
0.8448976401537943


## Prediction on Final Data

In [38]:
df2 = pd.read_csv('test.csv')
df2.head()

ID Tag  Reputation  Answers  Username    Views
0  366953   a      5645.0      3.0     50652  33200.0
1   71864   c     24511.0      6.0     37685   2730.0
2  141692   i       927.0      1.0    135293  21167.0
3  316833   i        21.0      6.0    166998  18528.0
4  440445   i      4475.0     10.0     53504  57240.0

In [49]:
X_T = df2.iloc[:, 1:] ## dropping ID variable
X_T.drop(['Username'], axis = 1, inplace = True)
X_T.head()

Tag  Reputation  Answers    Views
0   a      5645.0      3.0  33200.0
1   c     24511.0      6.0   2730.0
2   i       927.0      1.0  21167.0
3   i        21.0      6.0  18528.0
4   i      4475.0     10.0  57240.0

In [50]:
Tag = X_T['Tag']

## Dummies

In [51]:
## Convert tag into dummies.
X_T['Tag'] = Le.transform(X_T['Tag'])

In [52]:
X_T1 = X_T.copy()

In [47]:
##X_T = X_T1.copy()

In [55]:
X_T.head()

Tag  Reputation  Answers    Views
0    0      5645.0      3.0  33200.0
1    1     24511.0      6.0   2730.0
2    3       927.0      1.0  21167.0
3    3        21.0      6.0  18528.0
4    3      4475.0     10.0  57240.0

In [56]:
X_T = X_T.values

In [57]:
X_T = Ohencoder.transform(X_T).toarray()
##df= df.toarray()

In [58]:
X_T[0:3]

array([[1.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        5.6450e+03, 3.0000e+00, 3.3200e+04],
       [0.0000e+00, 1.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        2.4511e+04, 6.0000e+00, 2.7300e+03],
       [0.0000e+00, 0.0000e+00, 0.0000e+00, 1.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        9.2700e+02, 1.0000e+00, 2.1167e+04]])

In [59]:
X_T = pd.DataFrame(X_T)

In [60]:
X_T.head()

0    1    2    3    4    5    6    7    8    9        10    11       12
0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   5645.0   3.0  33200.0
1  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  24511.0   6.0   2730.0
2  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0    927.0   1.0  21167.0
3  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0     21.0   6.0  18528.0
4  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0   4475.0  10.0  57240.0

## Prediction

In [61]:
Upvotes = RF.predict(X_T)

In [62]:
Upvotes

array([227.26 ,  73.805,  33.185, ...,  77.44 ,  14.925,  21.535])

In [63]:
df2['Upvotes'] = Upvotes

In [64]:
df2.head()

ID Tag  Reputation  Answers  Username    Views  Upvotes
0  366953   a      5645.0      3.0     50652  33200.0  227.260
1   71864   c     24511.0      6.0     37685   2730.0   73.805
2  141692   i       927.0      1.0    135293  21167.0   33.185
3  316833   i        21.0      6.0    166998  18528.0   10.705
4  440445   i      4475.0     10.0     53504  57240.0  298.565

In [65]:
data_to_submit = df2[['ID', 'Upvotes']]

In [66]:
data_to_submit.head()

ID  Upvotes
0  366953  227.260
1   71864   73.805
2  141692   33.185
3  316833   10.705
4  440445  298.565

In [67]:
data_to_submit.to_csv('data_to_submit_RandomForest_withoutOutlierstreatment_02.csv',index=False)